Replace HTTParty with Faraday
ResultadosDigitais/agendor-ruby pull request #16
Opened 2021-03-05 02:42 UTC by andrehjr

2021-03-05 19:08 UTC, rafaelhancke requested changes

2021-03-05 19:08 UTC, rafaelhancke commented on lib/agendor/base.rb
> +        conn.headers = {'Content-Type' => 'application/json'}
@andrehjr , não é necessário definir o timeout aqui tbem?

2021-03-05 19:17 UTC, andrehjr commented on lib/agendor/base.rb
> +        conn.headers = {'Content-Type' => 'application/json'}
Podemos deixar configurável, o que acha?

2021-03-05 19:37 UTC, rafaelhancke commented on lib/agendor/base.rb
> +        conn.headers = {'Content-Type' => 'application/json'}
Pode ser sim, sem problemas

2021-03-05 20:53 UTC, andrehjr commented on lib/agendor/base.rb
> +        conn.headers = {'Content-Type' => 'application/json'}
Vou fazer isso no próximo PR, pode ser? Porque ai podemos adicionar um objeto de config aqui. Para poder configurar melhor o client.

O client antigo também não estava setando um timeout.

2021-03-08 13:27 UTC, rafaelhancke approved these changes
LGTM

2021-03-08 13:28 UTC, merged